<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13197" started-at="2020-04-20T13:15:31 IST" finished-at="2020-04-20T13:15:44 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="13197" started-at="2020-04-20T13:15:31 IST" finished-at="2020-04-20T13:15:44 IST">
      <class name="TestCases.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.LoginTest@5ef60048]" name="setUp" is-config="true" duration-ms="14693" started-at="2020-04-20T13:15:16 IST" finished-at="2020-04-20T13:15:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginToApp()[pri:1, instance:TestCases.LoginTest@5ef60048]" name="loginToApp" duration-ms="9059" started-at="2020-04-20T13:15:31 IST" finished-at="2020-04-20T13:15:40 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element Present on Page!! did not expect to find [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element Present on Page!! did not expect to find [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at TestCases.LoginTest.loginToApp(LoginTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
      </class> <!-- TestCases.LoginTest -->
      <class name="TestCases.HomeTest">
        <test-method status="PASS" signature="logOutApp()[pri:2, instance:TestCases.HomeTest@1d548a08]" name="logOutApp" duration-ms="4078" started-at="2020-04-20T13:15:40 IST" finished-at="2020-04-20T13:15:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutApp -->
      </class> <!-- TestCases.HomeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
